import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download } from "lucide-react";
import { useI18n } from "./i18n";

interface MetricSummary {
  name: string;
  current: string;
  range7d: string;
  range30d: string;
  range90d: string;
  trend: "improving" | "stable" | "concerning";
  notes: string;
}

interface ReportData {
  patient: {
    name: string;
    dob: string;
    gestation: string;
    location: string;
  };
  generatedAt: string;
  summary: string;
  metrics: MetricSummary[];
  events: { date: string; type: string; detail: string }[];
  medications: string[];
  providers: string[];
}

const SAMPLE: ReportData = {
  patient: {
    name: "Maria Santos",
    dob: "1994-03-12",
    gestation: "24 weeks (Second Trimester)",
    location: "Irvine, CA",
  },
  generatedAt: new Date().toISOString().slice(0, 10),
  summary:
    "Patient has been continuously monitored via a connected wearable since W12. Cardiovascular vitals trend stable with one episode of nocturnal tachycardia (W22) and intermittent BP elevation in the past 14 days. No medication changes since enrollment.",
  metrics: [
    { name: "Heart Rate (BPM)",       current: "72",     range7d: "68 – 88",   range30d: "62 – 104", range90d: "58 – 118", trend: "stable",      notes: "One episode > 110 BPM at rest (W22, 02:14)." },
    { name: "Blood Pressure (mmHg)",  current: "118/76", range7d: "112–124 / 72–80", range30d: "108–132 / 70–86", range90d: "104–138 / 68–90", trend: "concerning", notes: "Three readings > 130/85 in past 14 days. Recommend re-check." },
    { name: "Blood Sugar (mg/dL)",    current: "94",     range7d: "85 – 102",  range30d: "82 – 118", range90d: "80 – 124", trend: "stable",      notes: "Last lab draw 12 days ago." },
    { name: "Cholesterol (mg/dL)",    current: "182",    range7d: "—",         range30d: "178 – 192", range90d: "170 – 198", trend: "improving",  notes: "Last lab draw 47 days ago — consider new panel." },
    { name: "Steps / day",            current: "8,456",  range7d: "6,200 – 10,400", range30d: "4,800 – 11,300", range90d: "3,100 – 12,400", trend: "improving", notes: "Sustained increase since W18." },
    { name: "SpO₂ (%)",               current: "98",     range7d: "96 – 99",   range30d: "95 – 99",  range90d: "94 – 99",  trend: "stable",      notes: "No desaturation events." },
  ],
  events: [
    { date: "W22 D3", type: "Tachycardia",       detail: "HR peaked at 118 BPM at rest, 02:14. Resolved in 11 minutes." },
    { date: "W21 D5", type: "BP elevation",      detail: "138/88 mmHg morning reading. Patient reported headache." },
    { date: "W18 D1", type: "Activity milestone", detail: "First week averaging > 8,000 steps/day." },
  ],
  medications: ["Prenatal multivitamin (daily)", "Folic acid 800 mcg", "Low-dose aspirin 81 mg (per OB)"],
  providers: ["OB/GYN — Dr. L. Tran, Hoag", "Primary Care — Dr. R. Patel", "Cardiology consult — pending"],
};

const COLOR = {
  navy: [23, 46, 84] as [number, number, number],
  rose: [240, 106, 95] as [number, number, number],
  cream: [243, 239, 231] as [number, number, number],
  mute: [158, 135, 110] as [number, number, number],
};

function buildPdf(data: ReportData, lang: "en" | "es") {
  const L = lang === "es"
    ? {
        title: "Informe Longitudinal de Salud",
        subtitle: "Continuidad de cuidados — para cualquier proveedor",
        patient: "Paciente",
        generated: "Generado",
        gestation: "Gestación",
        summary: "Resumen Clínico",
        metrics: "Tendencias a Largo Plazo",
        current: "Actual",
        r7: "Rango 7d", r30: "Rango 30d", r90: "Rango 90d",
        trend: "Tendencia", notes: "Notas",
        events: "Eventos Notables",
        meds: "Medicamentos",
        prov: "Proveedores",
        footer: "Generado por HeraHealth — para reducir silos en la atención materna.",
        improving: "mejorando", stable: "estable", concerning: "preocupante",
      }
    : {
        title: "Longitudinal Health Report",
        subtitle: "Continuity-of-care summary — for any provider",
        patient: "Patient",
        generated: "Generated",
        gestation: "Gestation",
        summary: "Clinical Summary",
        metrics: "Long-Term Trends",
        current: "Current",
        r7: "7-day Range", r30: "30-day Range", r90: "90-day Range",
        trend: "Trend", notes: "Notes",
        events: "Notable Events",
        meds: "Medications",
        prov: "Care Team",
        footer: "Generated by HeraHealth — built to reduce silos in maternal care.",
        improving: "improving", stable: "stable", concerning: "concerning",
      };

  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(...COLOR.navy);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor(255, 253, 248);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("HeraHealth", 40, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(L.subtitle, 40, 58);

  // Title
  doc.setTextColor(...COLOR.navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(L.title, 40, 112);

  // Patient block
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLOR.mute);
  doc.text(`${L.patient}:`, 40, 140);
  doc.text(`${L.gestation}:`, 40, 156);
  doc.text(`${L.generated}:`, 320, 140);
  doc.setTextColor(...COLOR.navy);
  doc.setFont("helvetica", "bold");
  doc.text(`${data.patient.name} · DOB ${data.patient.dob} · ${data.patient.location}`, 110, 140);
  doc.text(data.patient.gestation, 110, 156);
  doc.text(data.generatedAt, 385, 140);

  // Summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(L.summary, 40, 192);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 70);
  const split = doc.splitTextToSize(data.summary, W - 80);
  doc.text(split, 40, 210);

  // Metrics table
  autoTable(doc, {
    startY: 210 + split.length * 13 + 18,
    head: [[L.metrics, L.current, L.r7, L.r30, L.r90, L.trend, L.notes]],
    body: data.metrics.map((m) => [
      m.name,
      m.current,
      m.range7d,
      m.range30d,
      m.range90d,
      L[m.trend],
      m.notes,
    ]),
    styles: { font: "helvetica", fontSize: 8.5, cellPadding: 5, textColor: COLOR.navy },
    headStyles: { fillColor: COLOR.navy, textColor: [255, 253, 248] },
    alternateRowStyles: { fillColor: COLOR.cream },
    columnStyles: { 6: { cellWidth: 130 } },
  });

  // Events
  // @ts-expect-error autotable adds this
  let y = doc.lastAutoTable.finalY + 24;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...COLOR.navy);
  doc.text(L.events, 40, y);
  autoTable(doc, {
    startY: y + 8,
    head: [["", "", ""]],
    body: data.events.map((e) => [e.date, e.type, e.detail]),
    showHead: "never",
    styles: { font: "helvetica", fontSize: 9.5, cellPadding: 5, textColor: COLOR.navy },
    alternateRowStyles: { fillColor: COLOR.cream },
  });

  // Meds + Providers two columns
  // @ts-expect-error
  y = doc.lastAutoTable.finalY + 24;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(L.meds, 40, y);
  doc.text(L.prov, W / 2 + 10, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  data.medications.forEach((m, i) => doc.text(`• ${m}`, 40, y + 18 + i * 14));
  data.providers.forEach((p, i) => doc.text(`• ${p}`, W / 2 + 10, y + 18 + i * 14));

  // Footer
  const ph = doc.internal.pageSize.getHeight();
  doc.setFillColor(...COLOR.cream);
  doc.rect(0, ph - 36, W, 36, "F");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(...COLOR.mute);
  doc.text(L.footer, 40, ph - 14);

  doc.save(`HeraHealth-Report-${data.generatedAt}.pdf`);
}

export function HealthReport() {
  const { t, lang } = useI18n();
  const [data] = useState<ReportData>(SAMPLE);

  return (
    <div className="p-6 max-w-5xl">
      <div className="flex items-center justify-between mb-6 gap-4 flex-wrap">
        <div>
          <h1 className="font-['Montserrat'] font-bold text-[28px] text-[#172e54] mb-1 flex items-center gap-2">
            <FileText size={26} /> {t("reportTitle")}
          </h1>
          <p className="font-['Poppins'] text-[14px] text-[#9e876e]">{t("reportSubtitle")}</p>
        </div>
        <Button
          onClick={() => buildPdf(data, lang)}
          className="rounded-full bg-[#f79891] text-[#172e54] hover:bg-[#f5867e] font-['Montserrat'] font-bold"
        >
          <Download size={16} /> {t("exportPdf")}
        </Button>
      </div>

      <Card className="bg-white p-6 rounded-[28px] border-2 border-[#f3efe7] mb-6">
        <p className="font-['Montserrat'] font-semibold text-[#172e54] mb-1">{data.patient.name}</p>
        <p className="font-['Poppins'] text-[13px] text-[#9e876e]">
          DOB {data.patient.dob} · {data.patient.gestation} · {data.patient.location}
        </p>
        <p className="font-['Poppins'] text-[14px] text-[#172e54]/85 mt-4 leading-relaxed">
          {data.summary}
        </p>
      </Card>

      <Card className="bg-white p-0 rounded-[28px] border-2 border-[#f3efe7] mb-6 overflow-hidden">
        <table className="w-full text-left font-['Poppins'] text-[13px]">
          <thead className="bg-[#172e54] text-white">
            <tr>
              <th className="p-3">Metric</th>
              <th className="p-3">Current</th>
              <th className="p-3">7-day</th>
              <th className="p-3">30-day</th>
              <th className="p-3">90-day</th>
              <th className="p-3">Trend</th>
            </tr>
          </thead>
          <tbody>
            {data.metrics.map((m, i) => (
              <tr key={m.name} className={i % 2 ? "bg-[#f3efe7]/40" : ""}>
                <td className="p-3 font-semibold text-[#172e54]">{m.name}</td>
                <td className="p-3 text-[#172e54]">{m.current}</td>
                <td className="p-3 text-[#172e54]/80">{m.range7d}</td>
                <td className="p-3 text-[#172e54]/80">{m.range30d}</td>
                <td className="p-3 text-[#172e54]/80">{m.range90d}</td>
                <td
                  className={`p-3 capitalize font-semibold ${
                    m.trend === "concerning"
                      ? "text-[#c63b30]"
                      : m.trend === "improving"
                      ? "text-green-700"
                      : "text-[#172e54]"
                  }`}
                >
                  {m.trend}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>

      <div className="grid grid-cols-2 gap-4">
        <Card className="bg-[#f3efe7] p-5 rounded-[28px] border-0">
          <h3 className="font-['Montserrat'] font-bold text-[#172e54] mb-2">Medications</h3>
          <ul className="space-y-1 font-['Poppins'] text-[13px] text-[#172e54]/85">
            {data.medications.map((m) => (
              <li key={m}>• {m}</li>
            ))}
          </ul>
        </Card>
        <Card className="bg-[#cfeafe] p-5 rounded-[28px] border-0">
          <h3 className="font-['Montserrat'] font-bold text-[#172e54] mb-2">Care Team</h3>
          <ul className="space-y-1 font-['Poppins'] text-[13px] text-[#172e54]/85">
            {data.providers.map((m) => (
              <li key={m}>• {m}</li>
            ))}
          </ul>
        </Card>
      </div>
    </div>
  );
}
